import { Scissors, Zap, ShieldCheck, Award, Star } from "lucide-react";
import type { BusinessTemplate } from "./types";

const suplidoraFenix: BusinessTemplate = {
  slug: "suplidora-fenix",
  industry: "Barber Supply",
  industryEs: "Suplidora de Barbería",
  websiteType: "Retail Showcase",
  defaultServicesField: "Venta de Equipos",
  siteVariant: "fenix",
  lockedLang: "es",
  brand: {
    name: "Suplidora Fénix",
    city: "San José",
    phone: "",
    phoneHref: "",
    email: "",
    address: "",
    heroIcon: Scissors,
    logo: "/template-assets/suplidora-fenix/fenix_logo.jpg",
    socials: {
      instagram: "https://www.instagram.com/suplidora_fenix",
    },
    palette: {
      primary: "#D4AF37",
      primaryDark: "#A98323",
      accent: "#D4AF37",
      heroFrom: "#0d0d0d",
      heroVia: "#111111",
      heroTo: "#000000",
      heroGlow1: "rgba(212,175,55,0.25)",
      heroGlow2: "rgba(212,175,55,0.15)",
      heroIconFrom: "#D4AF37",
      heroIconTo: "#A98323",
      contactFrom: "#0d0d0d",
      contactTo: "#000000",
    },
  },
  media: {
    hero: "/template-assets/suplidora-fenix/fenix_hero.jpg",
    heroVideo: "/template-assets/suplidora-fenix/fenix_hero_loop.mp4",
    heroPoster: "/template-assets/suplidora-fenix/fenix_hero_poster.jpg",
    video: "/template-assets/suplidora-fenix/fenix_band_loop.mp4",
    teamPortrait: "/template-assets/suplidora-fenix/fenix_owner.jpg",
    gallery: [
      "/template-assets/suplidora-fenix/fenix_clipper_kit.jpg",
      "/template-assets/suplidora-fenix/fenix_white_set.jpg",
      "/template-assets/suplidora-fenix/fenix_shaver_red.jpg",
      "/template-assets/suplidora-fenix/fenix_gold_shaver.jpg",
      "/template-assets/suplidora-fenix/fenix_vgr.jpg",
      "/template-assets/suplidora-fenix/fenix_gold_set.jpg",
      "/template-assets/suplidora-fenix/fenix_clipper_box.jpg",
      "/template-assets/suplidora-fenix/fenix_shaver_hands.jpg",
    ],
  },
  serviceIcons: [Zap, ShieldCheck, Award, Star],
  whyIcons: [Award, ShieldCheck, Zap, Star],
  content: {
    en: {
      nav: {
        services: "Categories",
        why: "About Us",
        process: "Brands",
        testimonials: "Products",
        faq: "FAQ",
        contact: "Instagram",
        call: "Message Us",
      },
      hero: {
        eyebrow: "COORDINATE YOUR PURCHASE VIA WHATSAPP · FOLLOW US @SUPLIDORA_FENIX",
        title1: "Professional Gear",
        title2: "For Barbers",
        subtitle: "Premium clippers, trimmers, and accessories from the industry's leading brands.",
        cta1: "Consult via WhatsApp",
        cta2: "View Catalog",
        badges: ["WMARK & VGR", "Barber Tools", "Check Availability"],
        ratingTitle: "Premium",
        ratingSubtitle: "Quality Tools",
        trustTitle: "Barber",
        trustSubtitle: "Supply Store",
      },
      services: {
        title: "Our Categories",
        blurb: "Equipment for your barber station.",
        items: [
          { title: "Clippers", blurb: "Clippers from different brands." },
          { title: "Trimmers", blurb: "Detail trimmers." },
          { title: "Shavers", blurb: "Foil shavers." },
          { title: "Dryers", blurb: "Hair dryers." },
          { title: "Accessories", blurb: "Guards and combs." },
          { title: "Barber Chairs", blurb: "Barber shop chairs." },
        ],
      },
      why: {
        title: "Equipment for Barbers",
        items: [
          { title: "Brands", blurb: "Catalog with options from WMARK, VGR, among others." },
          { title: "Barber Supplies", blurb: "Tools and accessories frequently used in barber shops." },
          { title: "Personalized Service", blurb: "Coordinate your purchase, payment options, and delivery directly via WhatsApp." },
          { title: "Catalog", blurb: "Browse our available categories." },
        ],
      },
      process: {
        title: "Top Brands",
        items: [
          { title: "WMARK", blurb: "Innovative cordless technology and reliable motors." },
          { title: "VGR", blurb: "Durable, ergonomic, and highly requested by pros." },
          { title: "Accessories", blurb: "Guards, capes, and everything else you need." },
          { title: "Furniture", blurb: "Premium barber chairs for your workspace." },
        ],
      },
      testimonials: {
        title: "Products",
        items: [
          { name: "Clippers", role: "Category", quote: "Precision and power for every fade." },
          { name: "Shavers", role: "Category", quote: "Zero-gap finishes." },
          { name: "Trimmers", role: "Category", quote: "Crisp lines guaranteed." },
        ],
      },
      faq: {
        title: "Frequently Asked Questions",
        items: [
          { q: "Do you ship nationwide?", a: "Ask our team about delivery options when you submit your consultation." },
          { q: "Are your products original?", a: "Consult with our team via WhatsApp." },
          { q: "How do I place an order?", a: "You can consult by adding products to 'My consultation' in our catalog and sending it directly via WhatsApp." },
          { q: "What brands do you carry?", a: "We specialize in WMARK and VGR, plus premium accessories." },
        ],
      },
      contact: {
        title: "Ready to Upgrade Your Gear?",
        blurb: "Follow us on Instagram to see our latest arrivals and place your order.",
        name: "Name",
        phone: "Phone",
        service: "Interested in",
        message: "Message",
        submit: "Send Message",
        success: "Message sent!",
        pick: "View More Products",
        services: ["Clippers", "Trimmers", "Shavers", "Other"],
      },
      footer: {
        tagline: "Your trusted barber supply store.",
        hours: "",
        rights: "All rights reserved.",
        hoursLabel: "",
      },
    },
    es: {
      nav: {
        services: "Categorías",
        why: "Nosotros",
        process: "Marcas",
        testimonials: "Productos",
        faq: "FAQ",
        contact: "Instagram",
        call: "Escríbenos",
      },
      hero: {
        eyebrow: "COORDINÁ TU COMPRA POR WHATSAPP · SÍGUENOS @SUPLIDORA_FENIX",
        title1: "Equipo Profesional",
        title2: "Para Barberos",
        subtitle: "Máquinas, trimmers y accesorios de primera calidad de las marcas líderes del mercado.",
        cta1: "Consultar por WhatsApp",
        cta2: "Ver Catálogo",
        badges: ["WMARK & VGR", "Herramientas de Barbería", "Consulta Disponibilidad"],
        ratingTitle: "Calidad",
        ratingSubtitle: "Herramientas Premium",
        trustTitle: "Suplidora",
        trustSubtitle: "De Barbería",
      },
      services: {
        title: "Nuestras Categorías",
        blurb: "Equipos para tu estación de barbería.",
        items: [
          { title: "Máquinas", blurb: "Máquinas de corte de diferentes marcas." },
          { title: "Trimmers", blurb: "Terminadoras de diferentes estilos." },
          { title: "Shavers", blurb: "Rasuradoras de lámina." },
          { title: "Secadoras", blurb: "Secadoras de cabello." },
          { title: "Accesorios", blurb: "Guías de colores y otros artículos." },
          { title: "Sillas de Barbero", blurb: "Sillas para estaciones de barbería." },
        ],
      },
      why: {
        title: "Equipos para Barbería",
        items: [
          { title: "Marcas en Catálogo", blurb: "Catálogo con opciones de WMARK, VGR, entre otros." },
          { title: "Insumos", blurb: "Herramientas y accesorios de uso frecuente en barberías." },
          { title: "Atención Personalizada", blurb: "Coordiná tu compra, opciones de pago y entrega directamente por WhatsApp." },
          { title: "Catálogo", blurb: "Revisá nuestras categorías disponibles." },
        ],
      },
      process: {
        title: "Marcas Top",
        items: [
          { title: "WMARK", blurb: "Tecnología inalámbrica innovadora y motores confiables." },
          { title: "VGR", blurb: "Duraderas, ergonómicas y altamente solicitadas por profesionales." },
          { title: "Accesorios", blurb: "Alzas, capas y todo lo demás que necesitas." },
          { title: "Mobiliario", blurb: "Sillas de barbero premium para tu espacio de trabajo." },
        ],
      },
      testimonials: {
        title: "Productos",
        items: [
          { name: "Clippers", role: "Categoría", quote: "Precisión y potencia para cada fade." },
          { name: "Shavers", role: "Categoría", quote: "Acabados al cero perfectos." },
          { name: "Trimmers", role: "Categoría", quote: "Líneas nítidas garantizadas." },
        ],
      },
      faq: {
        title: "Preguntas Frecuentes",
        items: [
          { q: "¿Hacen envíos a todo el país?", a: "Consultá opciones de entrega con nuestro equipo al realizar tu consulta." },
          { q: "¿Los productos son originales?", a: "Consultá con nuestro equipo por WhatsApp." },
          { q: "¿Cómo puedo hacer un pedido?", a: "Puedes realizar tu consulta agregando los productos a 'Mi consulta' en nuestro catálogo y enviándola directamente a través de nuestro WhatsApp." },
          { q: "¿Qué marcas manejan?", a: "Nos especializamos en WMARK y VGR, además de accesorios premium variados." },
        ],
      },
      contact: {
        title: "¿Listo para renovar tu equipo?",
        blurb: "Síguenos en Instagram para ver lo más nuevo y realizar tu pedido.",
        name: "Nombre",
        phone: "Teléfono",
        service: "Me interesa",
        message: "Mensaje",
        submit: "Enviar Mensaje",
        success: "¡Mensaje enviado!",
        pick: "Ver más productos",
        services: ["Máquinas", "Trimmers", "Shavers", "Otro"],
      },
      footer: {
        tagline: "Tu suplidora de barbería de confianza.",
        hours: "",
        rights: "Todos los derechos reservados.",
        hoursLabel: "",
      },
    },
  },
};

export default suplidoraFenix;